"""Tests for audit event list API endpoints."""

import os
import uuid
from unittest.mock import patch

import pytest
import sqlalchemy as sa
from alembic import command
from alembic.config import Config
from httpx import ASGITransport, AsyncClient
from sqlalchemy import create_engine, text


@pytest.fixture(scope="module")
def api_test_db():
    """Create an isolated test database for API tests."""
    db_name = f"harvester_audit_test_{uuid.uuid4().hex[:8]}"
    admin_url = "postgresql+psycopg://postgres:postgres123@192.168.0.114:5432/postgres"
    test_url = admin_url.rsplit("/", 1)[0] + "/" + db_name

    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{db_name}"'))
    admin_engine.dispose()

    env_backup = os.environ.pop("HARVESTER_DATABASE_URL", None)
    cfg = Config()
    cfg.set_main_option("script_location", "alembic")
    cfg.set_main_option("sqlalchemy.url", test_url)
    command.upgrade(cfg, "head")
    if env_backup:
        os.environ["HARVESTER_DATABASE_URL"] = env_backup

    yield test_url

    admin_engine2 = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin_engine2.connect() as conn:
        conn.execute(
            text(
                f"SELECT pg_terminate_backend(pid) FROM pg_stat_activity "
                f"WHERE datname = '{db_name}'"
            )
        )
        conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
    admin_engine2.dispose()


@pytest.fixture()
async def api_client(api_test_db):
    """Create an async API test client with database configured."""
    with patch.dict(
        os.environ,
        {
            "HARVESTER_API_TOKEN": "test-secret",
            "HARVESTER_DATABASE_URL": api_test_db,
        },
    ):
        from harvester.api.app import create_app

        app = create_app()
        transport = ASGITransport(app=app)
        async with AsyncClient(transport=transport, base_url="http://test") as client:
            yield client


# ---------------------------------------------------------------------------
# Task 1.1 — GET /audit/events basic tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_list_audit_events_requires_auth(api_client):
    """GET /audit/events without authentication should return 401."""
    resp = await api_client.get("/audit/events")
    assert resp.status_code in (401, 403)


@pytest.mark.asyncio
async def test_list_audit_events_returns_events(api_client):
    """GET /audit/events should return events generated by source operations."""
    # Arrange — create a source to generate audit events
    resp = await api_client.post(
        "/sources/propose",
        json={"name": f"audit-src-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )
    assert resp.status_code == 201

    # Act
    resp = await api_client.get(
        "/audit/events",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    assert "items" in data
    assert "total" in data
    assert isinstance(data["items"], list)
    assert data["total"] >= 1


@pytest.mark.asyncio
async def test_audit_events_have_expected_fields(api_client):
    """Audit event items should contain the required fields."""
    # Arrange — generate an audit event
    await api_client.post(
        "/sources/propose",
        json={"name": f"fields-src-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )

    # Act
    resp = await api_client.get(
        "/audit/events",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["items"]) >= 1
    event = data["items"][0]
    for field in ("id", "action", "entity_type", "created_at"):
        assert field in event, f"Missing required field: {field}"


@pytest.mark.asyncio
async def test_audit_events_sorted_by_created_at_desc(api_client):
    """GET /audit/events should return events sorted by created_at descending."""
    # Arrange — create three sources to generate ordered audit events
    tag = uuid.uuid4().hex[:6]
    names = [f"sort-audit-{i}-{tag}" for i in range(3)]
    for name in names:
        await api_client.post(
            "/sources/propose",
            json={"name": name, "kind": "web"},
            headers={"Authorization": "Bearer test-secret"},
        )

    # Act
    resp = await api_client.get(
        "/audit/events",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert — newest first
    assert resp.status_code == 200
    data = resp.json()
    events = data["items"]
    assert len(events) >= 3
    for i in range(len(events) - 1):
        assert events[i]["created_at"] >= events[i + 1]["created_at"]


@pytest.mark.asyncio
async def test_audit_events_pagination(api_client):
    """GET /audit/events should support limit and offset pagination."""
    # Arrange — create enough sources to test pagination
    tag = uuid.uuid4().hex[:6]
    for i in range(5):
        await api_client.post(
            "/sources/propose",
            json={"name": f"page-{i}-{tag}", "kind": "web"},
            headers={"Authorization": "Bearer test-secret"},
        )

    # Act — request first page
    resp = await api_client.get(
        "/audit/events?limit=2&offset=0",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["items"]) <= 2
    assert data["total"] >= 5


# ---------------------------------------------------------------------------
# Task 1.2 — GET /audit/events filter tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_filter_audit_events_by_entity_type(api_client):
    """GET /audit/events?entity_type=source should only return source events."""
    # Arrange
    await api_client.post(
        "/sources/propose",
        json={"name": f"filter-et-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )

    # Act
    resp = await api_client.get(
        "/audit/events?entity_type=source",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    for event in data["items"]:
        assert event["entity_type"] == "source"


@pytest.mark.asyncio
async def test_filter_audit_events_by_entity_id(api_client):
    """GET /audit/events?entity_id=X should only return events for that entity."""
    # Arrange
    resp = await api_client.post(
        "/sources/propose",
        json={"name": f"filter-eid-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )
    source_id = resp.json()["id"]

    # Act
    resp = await api_client.get(
        f"/audit/events?entity_type=source&entity_id={source_id}",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["items"]) >= 1
    for event in data["items"]:
        assert event["entity_id"] == source_id


@pytest.mark.asyncio
async def test_filter_audit_events_by_action(api_client):
    """GET /audit/events?action=source.propose should only return propose events."""
    # Arrange
    await api_client.post(
        "/sources/propose",
        json={"name": f"filter-act-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )

    # Act
    resp = await api_client.get(
        "/audit/events?action=source.propose",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["items"]) >= 1
    for event in data["items"]:
        assert event["action"] == "source.propose"


@pytest.mark.asyncio
async def test_filter_audit_events_by_actor(api_client):
    """GET /audit/events?actor=api should only return events by api actor."""
    # Arrange
    await api_client.post(
        "/sources/propose",
        json={"name": f"filter-actor-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )

    # Act
    resp = await api_client.get(
        "/audit/events?actor=api",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["items"]) >= 1
    for event in data["items"]:
        assert event["actor"] == "api"


@pytest.mark.asyncio
async def test_filter_audit_events_by_time_range(api_client):
    """GET /audit/events with time_from/time_to should filter by created_at."""
    # Arrange — create a source to generate an audit event
    resp = await api_client.post(
        "/sources/propose",
        json={"name": f"filter-time-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )
    assert resp.status_code == 201

    # Act — use a far-future time_to to get zero results
    resp = await api_client.get(
        "/audit/events?time_from=2099-01-01T00:00:00Z",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert — no events in the future
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["items"]) == 0


# ---------------------------------------------------------------------------
# Task 1.3 — No raw payload in audit response
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_audit_events_do_not_expose_raw_payload_fields(api_client):
    """Audit event response should not include before_state/after_state raw JSONB."""
    # Arrange
    await api_client.post(
        "/sources/propose",
        json={"name": f"no-raw-{uuid.uuid4().hex[:6]}", "kind": "web"},
        headers={"Authorization": "Bearer test-secret"},
    )

    # Act
    resp = await api_client.get(
        "/audit/events",
        headers={"Authorization": "Bearer test-secret"},
    )

    # Assert — the response should contain summary fields, not raw state
    assert resp.status_code == 200
    data = resp.json()
    for event in data["items"]:
        # Raw before_state/after_state JSONB must not be present
        assert "before_state" not in event, "before_state must not be exposed"
        assert "after_state" not in event, "after_state must not be exposed"
        # Summary fields should be present instead
        assert "before_summary" in event
        assert "after_summary" in event
