import { expect, test } from '@playwright/test'

test.describe('Audit Log E2E', () => {
  test.beforeEach(async ({ page }) => {
    // Navigate to the app and configure API connection
    await page.goto('/')
    await page.evaluate(() => localStorage.clear())
    await page.reload()

    // Configure API base URL if not already configured
    const configForm = page.getByTestId('api-config-form')
    if (await configForm.isVisible()) {
      await page.getByTestId('input-api-base-url').fill('http://localhost:8001')
      await page.getByTestId('input-api-token').fill('test-secret')
      await page.getByTestId('save-config-button').click()
    }
  })

  test('navigates to the audit log page', async ({ page }) => {
    await page.getByTestId('nav-audit').click()

    await expect(page.getByTestId('page-audit-log')).toBeVisible()
    await expect(page.getByText('Audit Log')).toBeVisible()
  })

  test('shows audit events generated by source operations', async ({ page }) => {
    // First create a source to generate an audit event
    await page.getByTestId('nav-sources').click()
    await expect(page.getByTestId('page-sources')).toBeVisible()

    await page.getByTestId('new-source-button').click()
    const uniqueName = `e2e-audit-src-${Date.now()}`
    await page.getByTestId('input-source-name').fill(uniqueName)
    await page.getByTestId('input-source-url').fill('https://audit-test.example.com')
    await page.getByTestId('submit-propose-source').click()
    await expect(page.getByText(uniqueName)).toBeVisible()

    // Navigate to the audit log page
    await page.getByTestId('nav-audit').click()
    await expect(page.getByTestId('page-audit-log')).toBeVisible()

    // Wait for audit events to load
    await expect(page.getByTestId('audit-timeline')).toBeVisible()

    // Should see the source.propose action for our source
    await expect(page.getByText('source.propose')).toBeVisible()
  })

  test('shows empty state when no events match filters', async ({ page }) => {
    await page.getByTestId('nav-audit').click()
    await expect(page.getByTestId('page-audit-log')).toBeVisible()

    // Wait for initial load
    await expect(
      page.getByTestId('audit-timeline').or(page.getByTestId('audit-empty')),
    ).toBeVisible()

    // Filter to a far-future time range that should yield no results
    // Select an action that might not have events
    await page.getByTestId('select-action-filter').selectOption('crawl.complete')

    // Wait for the filtered results to load — timeline updates after fetch
    await expect(
      page.getByTestId('audit-timeline').or(page.getByTestId('audit-empty')),
    ).toBeVisible()
  })

  test('filters audit events by entity type', async ({ page }) => {
    // Create a source first
    await page.getByTestId('nav-sources').click()
    await page.getByTestId('new-source-button').click()
    const uniqueName = `e2e-filter-audit-${Date.now()}`
    await page.getByTestId('input-source-name').fill(uniqueName)
    await page.getByTestId('submit-propose-source').click()
    await expect(page.getByText(uniqueName)).toBeVisible()

    // Navigate to audit log
    await page.getByTestId('nav-audit').click()
    await expect(page.getByTestId('page-audit-log')).toBeVisible()
    await expect(page.getByTestId('audit-timeline')).toBeVisible()

    // Filter by source entity type
    await page.getByTestId('select-entity-type-filter').selectOption('source')

    // Wait for filtered results to load
    await expect(
      page.getByTestId('audit-timeline').or(page.getByTestId('audit-empty')),
    ).toBeVisible()

    // All visible events should be source events
    const timeline = page.getByTestId('audit-timeline')
    await expect(timeline).toBeVisible()
  })

  test('refreshes audit events', async ({ page }) => {
    await page.getByTestId('nav-audit').click()
    await expect(page.getByTestId('page-audit-log')).toBeVisible()

    // Wait for initial load
    await expect(
      page.getByTestId('audit-timeline').or(page.getByTestId('audit-empty')),
    ).toBeVisible()

    // Click refresh
    await page.getByTestId('refresh-audit').click()

    // Page should still be visible
    await expect(page.getByTestId('page-audit-log')).toBeVisible()
  })

  test('displays event details without raw payload', async ({ page }) => {
    // Create a source to generate audit event
    await page.getByTestId('nav-sources').click()
    await page.getByTestId('new-source-button').click()
    const uniqueName = `e2e-detail-audit-${Date.now()}`
    await page.getByTestId('input-source-name').fill(uniqueName)
    await page.getByTestId('submit-propose-source').click()
    await expect(page.getByText(uniqueName)).toBeVisible()

    // Navigate to audit log
    await page.getByTestId('nav-audit').click()
    await expect(page.getByTestId('page-audit-log')).toBeVisible()
    await expect(page.getByTestId('audit-timeline')).toBeVisible()

    // Verify event shows action pill and entity type
    await expect(page.getByText('source.propose')).toBeVisible()

    // Verify timeline does NOT contain raw payload fields
    const timelineContent = await page.getByTestId('audit-timeline').textContent()
    expect(timelineContent).not.toContain('before_state')
    expect(timelineContent).not.toContain('after_state')
  })
})
